"""
Pydantic data models for the research pipeline.
"""

from pydantic import BaseModel, Field
from typing import Optional
from datetime import datetime


# ── Paper Models ──────────────────────────────────────────────

class Paper(BaseModel):
    """A retrieved research paper."""
    arxiv_id: str
    title: str
    authors: list[str]
    abstract: str
    published: str
    url: str
    pdf_url: str = ""


class PaperSummary(BaseModel):
    """Structured summary extracted from a paper."""
    paper_title: str
    problem_statement: str
    proposed_method: str
    dataset_used: str
    evaluation_results: str
    limitations: str
    key_contributions: str


# ── Analysis Models ───────────────────────────────────────────

class ResearchGap(BaseModel):
    """An identified gap in existing research."""
    description: str
    severity: str = "medium"
    source_papers: list[str] = Field(default_factory=list)
    research_direction: str = ""


class Hypothesis(BaseModel):
    """A generated research hypothesis."""
    title: str
    description: str
    proposed_approach: str
    expected_outcome: str
    justification: str


# ── Notebook / Experiment Models ──────────────────────────────

class NotebookCell(BaseModel):
    """A single cell in the experiment notebook."""
    cell_id: str
    cell_type: str = "code"  # code, markdown
    title: str = ""
    code: str = ""
    description: str = ""


class CellExecutionResult(BaseModel):
    """Result from executing a notebook cell."""
    cell_id: str
    success: bool
    stdout: str = ""
    stderr: str = ""
    images: list[str] = Field(default_factory=list)  # base64 PNGs
    error: str = ""
    execution_time: float = 0.0


class ExperimentCode(BaseModel):
    """Generated ML experiment as notebook cells."""
    cells: list[NotebookCell] = Field(default_factory=list)
    explanation: str = ""
    requirements: str = ""


# ── Evaluation Models ─────────────────────────────────────────

class EvaluationResult(BaseModel):
    """Evaluation of the experiment (uses real execution results when available)."""
    estimated_accuracy: str
    estimated_f1: str
    estimated_precision: str
    estimated_recall: str
    comparison_with_baselines: str
    strengths: str
    limitations: str
    overall_assessment: str


# ── Report Models ─────────────────────────────────────────────

class ResearchReport(BaseModel):
    """The final generated research report."""
    title: str
    abstract: str
    introduction: str
    literature_review: str
    methodology: str
    experiment_setup: str
    results: str
    discussion: str
    conclusion: str
    references: str


# ── Pipeline Event Model (for SSE streaming) ─────────────────

class PipelineEvent(BaseModel):
    """An event emitted during pipeline execution for real-time UI updates."""
    stage: str
    status: str
    message: str
    data: Optional[dict] = None
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat())


# ── Research Plan ─────────────────────────────────────────────

class ResearchPlan(BaseModel):
    """The research plan generated by the Planner Agent."""
    topic: str
    refined_topic: str
    search_queries: list[str]
    research_objectives: list[str]
    methodology_notes: str
    expected_output: str


# ── Chat Models ───────────────────────────────────────────────

class ChatMessage(BaseModel):
    """A chat message in the notebook."""
    role: str  # user, assistant
    content: str


class ChatRequest(BaseModel):
    """Request for the agent chat."""
    message: str
    context: str = ""  # agent-specific context
    agent: str = "general"  # which agent to chat with
