"""
Critic Agent — Reviews and evaluates research plans and hypotheses generated by other agents.
Can demand rewrites and highlight logical flaws or lack of novelty.
"""

import json
import traceback
from backend.tools.llm_client import call_llm_json

class ReviewResult:
    def __init__(self, passed: bool, feedback: str, score: int):
        self.passed = passed
        self.feedback = feedback
        self.score = score

CRITIC_PLAN_PROMPT = """You are a brutal, uncompromising Senior Research Scientist (Critic Agent).
Your job is to review the Research Plans generated by an AI Planner.

You must evaluate the plans based on:
1. Novelty (Is this actually new, or just a slight tweak of existing work?)
2. Feasibility (Can this be executed realistically on standard accessible hardware?)
3. Logical Soundness (Does the proposed methodology actually solve the sub-problem?)
4. Specificity (Are the datasets and metrics concrete, or vague?)

You MUST respond with valid JSON in this exact format:
{
  "passed": true|false,
  "score": 8,
  "harsh_feedback": "Detailed paragraph explaining the flaws, what is missing, and explicitly what the Planner MUST change in the next iteration."
}

Rules for Passing:
- ONLY return "passed": true if the plans are exceptionally novel and specific (Score >= 8).
- If the plans are generic, safe, or lack concrete datasets/methods, return "passed": false and demand a rewrite.
"""

CRITIC_HYPOTHESIS_PROMPT = """You are a brutal, uncompromising Senior Research Scientist (Critic Agent).
Your job is to review the Research Hypotheses generated by an AI Hypothesis Generator.

You must evaluate the hypotheses based on:
1. Grounding (Are they firmly rooted in the provided paper summaries and gaps?)
2. Testability (Can they actually be proven/disproven with an ML experiment?)
3. Impact (Will solving this hypothesis advance the field meaningfully?)

You MUST respond with valid JSON in this exact format:
{
  "passed": true|false,
  "score": 8,
  "harsh_feedback": "Detailed paragraph explaining the flaws, what is missing, and explicitly what the Hypothesis agent MUST change in the next iteration."
}

Rules for Passing:
- ONLY return "passed": true if the hypotheses are testable and impactful (Score >= 8).
- If the hypotheses are untestable, ungrounded, or trivial, return "passed": false and demand a rewrite.
"""

async def review_plans(topic: str, plans_data: dict, attempt: int = 1) -> ReviewResult:
    """Critique the generated plans. Returns whether they pass the quality bar."""
    
    # If we've already tried several times, force a pass to avoid infinite loops
    if attempt >= 3:
        return ReviewResult(passed=True, feedback="Forced pass after max attempts.", score=7)
        
    user_prompt = f"""Review these research plans for the topic: {topic}

Plans Context:
{json.dumps(plans_data.get('plans', []), indent=2)}

Do they meet the highest standards of novelty and specificity? Provide your brutal critique."""

    try:
        result = await call_llm_json(
            system_prompt=CRITIC_PLAN_PROMPT,
            user_prompt=user_prompt,
            temperature=0.3,
            max_tokens=1000,
        )
        passed = bool(result.get("passed", False))
        feedback = str(result.get("harsh_feedback", "No feedback provided."))
        score = int(result.get("score", 5))
        return ReviewResult(passed=passed, feedback=feedback, score=score)
        
    except Exception as e:
        print(f"[Critic Agent] Error during plan review: {e}")
        traceback.print_exc()
        return ReviewResult(passed=True, feedback=f"Critic failed, defaulting to pass: {e}", score=5)

async def review_hypotheses(topic: str, gaps_data: list, hypotheses_data: list, attempt: int = 1) -> ReviewResult:
    """Critique the generated hypotheses. Returns whether they pass the quality bar."""
    
    if attempt >= 3:
        return ReviewResult(passed=True, feedback="Forced pass after max attempts.", score=7)
        
    user_prompt = f"""Review these hypotheses for the topic: {topic}

Identified Gaps:
{json.dumps(gaps_data, indent=2)}

Generated Hypotheses:
{json.dumps(hypotheses_data, indent=2)}

Are these testable, impactful, and grounded in the gaps? Provide your brutal critique."""

    try:
        result = await call_llm_json(
            system_prompt=CRITIC_HYPOTHESIS_PROMPT,
            user_prompt=user_prompt,
            temperature=0.3,
            max_tokens=1000,
        )
        passed = bool(result.get("passed", False))
        feedback = str(result.get("harsh_feedback", "No feedback provided."))
        score = int(result.get("score", 5))
        return ReviewResult(passed=passed, feedback=feedback, score=score)
        
    except Exception as e:
        print(f"[Critic Agent] Error during hypothesis review: {e}")
        traceback.print_exc()
        return ReviewResult(passed=True, feedback=f"Critic failed, defaulting to pass: {e}", score=5)
